#
# Copyright (c) 2012-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation

name: Code Coverage Report
on: [push, pull_request]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Test backend-shared
        run: make test
        working-directory: ./backend-shared
      - name: Test backend
        run: make test
        working-directory: ./backend
      - name: Test cluster-agent
        run: make test
        working-directory: ./backend
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
